apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    name: mean-app-mongo-service
    app: mean-app-webpage
    type: mongo-service
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: mean-app-mongo-pod
    app: mean-app-webpage