apiVersion: v1
kind: Service
metadata:
  name: mean-app-expressnode-service
  labels:
    name: mean-app-expressnode-service
    app: mean-app-webpage
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    name: mean-app-expressnode-pod
    app: mean-app-webpage