apiVersion: v1
kind: Pod
metadata:
  name: mean-app-mongo-pod
  labels:
    name: mean-app-mongo-pod
    app: mean-app-webpage
    type: mongo-db
spec:
    containers:
      - name: mean-app-mongo-container
        image: mongo
        ports:
          - containerPort: 27017
            protocol: TCP
