apiVersion: v1
kind: Service
metadata:
  name: mean-app-angular-service
  labels:
    name: mean-app-angular-service
    app: mean-app-webpage
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 4200
      nodePort: 4200
  selector:
    name: mean-app-angular-pod
    app: mean-app-webpage